#############################################################################
# Makefile for building: Symlink
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Jul 2 21:55:18 2017
# Project:  ../Symlink/Symlink.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile ../Symlink/Symlink.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I../Symlink -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I../Symlink -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Symlink/main.cpp \
		../Symlink/mainwindow.cpp \
		../Symlink/finished.cpp \
		../Symlink/mkdirectory.cpp \
		../Symlink/dirresult.cpp \
		../Symlink/manlinkname.cpp \
		../Symlink/error.cpp moc_mainwindow.cpp \
		moc_finished.cpp \
		moc_mkdirectory.cpp \
		moc_dirresult.cpp \
		moc_manlinkname.cpp \
		moc_error.cpp
OBJECTS       = main.o \
		mainwindow.o \
		finished.o \
		mkdirectory.o \
		dirresult.o \
		manlinkname.o \
		error.o \
		moc_mainwindow.o \
		moc_finished.o \
		moc_mkdirectory.o \
		moc_dirresult.o \
		moc_manlinkname.o \
		moc_error.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../Symlink/Symlink.pro
QMAKE_TARGET  = Symlink
DESTDIR       = 
TARGET        = Symlink

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_finished.h ui_mkdirectory.h ui_dirresult.h ui_manlinkname.h ui_error.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Symlink/Symlink.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile ../Symlink/Symlink.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile ../Symlink/Symlink.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Symlink1.0.0 || $(MKDIR) .tmp/Symlink1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Symlink1.0.0/ && $(COPY_FILE) --parents ../Symlink/mainwindow.h ../Symlink/finished.h ../Symlink/mkdirectory.h ../Symlink/dirresult.h ../Symlink/manlinkname.h ../Symlink/error.h .tmp/Symlink1.0.0/ && $(COPY_FILE) --parents ../Symlink/main.cpp ../Symlink/mainwindow.cpp ../Symlink/finished.cpp ../Symlink/mkdirectory.cpp ../Symlink/dirresult.cpp ../Symlink/manlinkname.cpp ../Symlink/error.cpp .tmp/Symlink1.0.0/ && $(COPY_FILE) --parents ../Symlink/mainwindow.ui ../Symlink/finished.ui ../Symlink/mkdirectory.ui ../Symlink/dirresult.ui ../Symlink/manlinkname.ui ../Symlink/error.ui .tmp/Symlink1.0.0/ && (cd `dirname .tmp/Symlink1.0.0` && $(TAR) Symlink1.0.0.tar Symlink1.0.0 && $(COMPRESS) Symlink1.0.0.tar) && $(MOVE) `dirname .tmp/Symlink1.0.0`/Symlink1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Symlink1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_finished.cpp moc_mkdirectory.cpp moc_dirresult.cpp moc_manlinkname.cpp moc_error.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_finished.cpp moc_mkdirectory.cpp moc_dirresult.cpp moc_manlinkname.cpp moc_error.cpp
moc_mainwindow.cpp: ../Symlink/finished.h \
		../Symlink/error.h \
		../Symlink/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ../Symlink/mainwindow.h -o moc_mainwindow.cpp

moc_finished.cpp: ../Symlink/finished.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ../Symlink/finished.h -o moc_finished.cpp

moc_mkdirectory.cpp: ../Symlink/mkdirectory.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ../Symlink/mkdirectory.h -o moc_mkdirectory.cpp

moc_dirresult.cpp: ../Symlink/dirresult.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ../Symlink/dirresult.h -o moc_dirresult.cpp

moc_manlinkname.cpp: ../Symlink/manlinkname.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ../Symlink/manlinkname.h -o moc_manlinkname.cpp

moc_error.cpp: ../Symlink/error.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ../Symlink/error.h -o moc_error.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_finished.h ui_mkdirectory.h ui_dirresult.h ui_manlinkname.h ui_error.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_finished.h ui_mkdirectory.h ui_dirresult.h ui_manlinkname.h ui_error.h
ui_mainwindow.h: ../Symlink/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../Symlink/mainwindow.ui -o ui_mainwindow.h

ui_finished.h: ../Symlink/finished.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../Symlink/finished.ui -o ui_finished.h

ui_mkdirectory.h: ../Symlink/mkdirectory.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../Symlink/mkdirectory.ui -o ui_mkdirectory.h

ui_dirresult.h: ../Symlink/dirresult.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../Symlink/dirresult.ui -o ui_dirresult.h

ui_manlinkname.h: ../Symlink/manlinkname.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../Symlink/manlinkname.ui -o ui_manlinkname.h

ui_error.h: ../Symlink/error.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../Symlink/error.ui -o ui_error.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../Symlink/main.cpp ../Symlink/mainwindow.h \
		../Symlink/finished.h \
		../Symlink/error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Symlink/main.cpp

mainwindow.o: ../Symlink/mainwindow.cpp ../Symlink/mainwindow.h \
		../Symlink/finished.h \
		../Symlink/error.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../Symlink/mainwindow.cpp

finished.o: ../Symlink/finished.cpp ../Symlink/finished.h \
		ui_finished.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o finished.o ../Symlink/finished.cpp

mkdirectory.o: ../Symlink/mkdirectory.cpp ../Symlink/mkdirectory.h \
		ui_mkdirectory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mkdirectory.o ../Symlink/mkdirectory.cpp

dirresult.o: ../Symlink/dirresult.cpp ../Symlink/dirresult.h \
		ui_dirresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dirresult.o ../Symlink/dirresult.cpp

manlinkname.o: ../Symlink/manlinkname.cpp ../Symlink/manlinkname.h \
		ui_manlinkname.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manlinkname.o ../Symlink/manlinkname.cpp

error.o: ../Symlink/error.cpp ../Symlink/error.h \
		ui_error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o error.o ../Symlink/error.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_finished.o: moc_finished.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_finished.o moc_finished.cpp

moc_mkdirectory.o: moc_mkdirectory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mkdirectory.o moc_mkdirectory.cpp

moc_dirresult.o: moc_dirresult.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dirresult.o moc_dirresult.cpp

moc_manlinkname.o: moc_manlinkname.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_manlinkname.o moc_manlinkname.cpp

moc_error.o: moc_error.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_error.o moc_error.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

